version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install -g snyk
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - pip install truffleHog
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_Linux.tar.gz
      - tar -xvzf ZAP_2.14.0_Linux.tar.gz
      - export PATH=$PATH:$(pwd)/ZAP_2.14.0

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - REPO_URI=$ECR_REPOSITORY_URI

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - echo Scanning with Trivy...
      - ./trivy image --exit-code 1 --severity HIGH $REPO_URI:$IMAGE_TAG
      - echo Scanning with Snyk...
      - snyk test --docker $REPO_URI:$IMAGE_TAG || true
      - echo Scanning with TruffleHog...
      - trufflehog filesystem . || true
      - echo Starting ZAP scan...
      - ./ZAP_2.14.0/zap.sh -cmd -quickurl http://yourapp-url.com -quickout zap_report.html || true

  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPO_URI:$IMAGE_TAG

artifacts:
  files:
    - zap_report.html
