version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade pip
      - pip install flask
      - npm install -g snyk
      - pip install trufflehog
      - echo "Tools installed"

  pre_build:
    commands:
      - snyk auth $SNYK_TOKEN
      - snyk test --file=app/requirements.txt --sarif-file-output=snyk.sarif || true
      - snyk monitor --file=app/requirements.txt
      - trufflehog filesystem . --json > trufflehog.json || true

  build:
    commands:
      - docker build -t vulnerable-app .
      - docker run -d -p 8080:8080 --name vuln-demo vulnerable-app
      - sleep 10  # give the container time to start

  post_build:
    commands:
      - echo "Running OWASP ZAP in Docker..."
      - docker run --network="host" -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zap-stable zap-baseline.py -t http://localhost:8080 -r zap-report.html || true

artifacts:
  files:
    - zap-report.html
    - snyk.sarif
    - trufflehog.json
